### ISSUE TITLE
Add a default config for remote debuging over local network

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/neodymium#10]
Enforce localnetwork debug to improve good practice.

Use the right flag:
`--remote-debugging-port=9222`

Use the right command-line as a node script: 
`ssh -L 0.0.0.0:9223:localhost:9222 localhost -N`

Then tell the user / developper the remote console is available here : 
`http://<IPADDRESS>:<PORT>`

This will help to stay out of `console.log()`debug and help user playing with `breakpoint`. It will also avoid `console state` build which is kind of a nonsens.

What do you think of that.

**Comment by gabrielstuff** [comment]
Just added the remote-debugging option. Looking forward to get a clean `npm start` that would allow this.

**Comment by hugohil** [comment]
I'll take a look. Could you please follow the contribution guidelines for futures updates : https://github.com/soixantecircuits/neodymium#contributing .
I'll create the `feature-remote-debug`.
